# Generated by Django 3.2 on 2022-01-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220116_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.CharField(default='xx@gmail.com', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_trainer_code',
            field=models.CharField(default='XXX-XXXX-XXX', max_length=20),
        ),
    ]
