# Generated by Django 3.2 on 2022-01-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20220116_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribed',
        ),
    ]
