# Generated by Django 3.2 on 2022-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
