# Generated by Django 3.2 on 2022-01-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='subscribed',
        ),
    ]
