# Generated by Django 3.0.1 on 2022-02-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220224_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
