# Generated by Django 3.2.9 on 2021-11-29 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilities', models.CharField(max_length=30)),
                ('type2', models.CharField(max_length=20)),
                ('attack', models.IntegerField(default=1)),
                ('defense', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=20)),
                ('sp_attack', models.IntegerField(default=1)),
                ('sp_defense', models.IntegerField(default=1)),
                ('speed', models.IntegerField(default=1)),
                ('generation', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
