# Generated by Django 3.2 on 2021-12-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_info_pdex_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='generation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='hp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='pdex_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='sp_attack',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='sp_defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
