# Generated by Django 3.2 on 2022-01-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_info_owner_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='type2',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='typ2', to='goods.category'),
        ),
    ]
